# jcmd-openjdk19
# Autogenerated from man page /usr/share/man/man1/jcmd-openjdk19.1.gz
complete -c jcmd-openjdk19 -o all -d 'Compiler. codecache Prints code cache layout and bounds.  Impact: Low'
complete -c jcmd-openjdk19 -o parallel -d 'heap inspection'
complete -c jcmd-openjdk19 -o gz -d 'gzipped format using the given compression level'
complete -c jcmd-openjdk19 -o overwrite -d 'overwritten if it exists (BOOLEAN, false)'
complete -c jcmd-openjdk19 -s e -d 'false) [bu] 2'
complete -c jcmd-openjdk19 -s l -d '(BOOLEAN, false) VM'
complete -c jcmd-openjdk19 -s i -d '(BOOLEAN, false) [bu] 2'
complete -c jcmd-openjdk19 -s s -d 'subclasses in addition to its superclasses'
complete -c jcmd-openjdk19 -o verbose -d 'table (BOOLEAN, false) VM. symboltable [options] Dumps the symbol table'
complete -c jcmd-openjdk19 -o date -d '(BOOLEAN, false) VM. version Prints JVM version information.  Impact: Low'

