# jstack-openjdk19
# Autogenerated from man page /usr/share/man/man1/jstack-openjdk19.1.gz
complete -c jstack-openjdk19 -s l -d 'The long listing option prints additional information about locks'
complete -c jstack-openjdk19 -s h -o help -d 'Prints a help message'

